name: CICD Pipeline

on:
  workflow_dispatch

jobs: 
  code:
    
      runs-on: ubuntu-latest
      steps:
      - name : Code is fetched from repo
        run: echo "code runs successfully"

 
  build:
      needs : [code]
      runs-on: ubuntu-latest
      steps:
      - name : Build is performed
        run: echo "Build runs successfully"

  test:
      needs : [build]
      runs-on: ubuntu-latest
      steps:
      - name : Test is performed
        run: echo "Test performed successfully"

  deploy:
      needs : [test]
      runs-on : ubuntu-latest
      steps:
      - name: deployment successfully
        run: echo "Docker file deployed"
