name: hello
on: 
  push:
    branches: [main]

jobs:
  koshish:
    runs-on : ubuntu-latest

    steps:
      - name: hello
        run: echo "Hello Dosto"

      - name: dosto
        run: echo "Hello $USER"

  mazedar:
    runs-on: ubuntu-latest

    steps:
      - name: version of docker and python
        run: echo "docker --version && python --version" 
      
